### ISSUE TITLE
Ingest UI unnecessary polling pages every 5 seconds

### ISSUE THREAD

**Issue by ke4** [ebi-ait/dcp-ingest-central#328]
Steps to reproduce:

1. Log into Ingest UI.
2. Click on the All submissions link.
3. Open Web developer tool and go to the Network tab

Notice that every 5 seconds the page refreshing itself.
I am not sure it is necessary on this page.
You can also notice that most of the response is 200, but there are some 500 as well.

We should investigate if this polling is really necessary and if not then remove it.
The auto-save feature might causing this, but it is just a wild guess.

**Comment by jacobwindsor** [comment]
I think is no longer the case right? This was fixed with https://github.com/ebi-ait/ingest-ui/pull/75

@ke4

**Comment by ke4** [comment]
@jacobwindsor I tested this on dev and unfortunately it is still happening.
![Screenshot 2021-09-21 at 10.12.04.png](https://images.zenhubusercontent.com/5f2957fd448645a503a32777/dac1a843-d567-42aa-a7c5-2fd1ca7aa170)

**Comment by jacobwindsor** [comment]
This has been fixed in https://github.com/ebi-ait/ingest-ui

**Comment by jacobwindsor** [comment]
This has been fixed in https://github.com/ebi-ait/ingest-ui
